name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8

    - name: Build with Gradle
      run: chmod +x gradlew &&./gradlew assemblerelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/pub/release/*.apk
        if-no-files-found: warn
        retention-days: 7